import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { option, sha256File } from './common.js';
const manifestPath=resolve(option('manifest') ?? 'artifacts/manifest.json');
const manifest=JSON.parse(readFileSync(manifestPath,'utf8')) as Record<string,unknown>;
const artifactPath=resolve(option('artifact') ?? `artifacts/${String(manifest.fileName)}`);
if (option('authorize') !== 'release-authoring') throw new Error('Refusing to rewrite the tracked trust root without --authorize=release-authoring.');
manifest.sha256=sha256File(artifactPath);
writeFileSync(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);
console.log(manifest.sha256);
