import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { option, sha256File } from './common.js';
const manifestPath=resolve(option('manifest') ?? 'artifacts/manifest.json');
const artifactPath=resolve(option('artifact') ?? 'artifacts/words-of-word-lexicon-v0.1.0.sqlite');
const manifest=JSON.parse(readFileSync(manifestPath,'utf8')) as Record<string,unknown>;
if (option('authorize') !== 'release-authoring') throw new Error('Refusing to rewrite the tracked trust root without --authorize=release-authoring.');
manifest.sha256=sha256File(artifactPath);
manifest.note='Unpublished deterministic Phase-1 artifact. Build locally with pnpm lexicon:build; publishing requires an immutable URL and a separately reviewed release.';
writeFileSync(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);
console.log(manifest.sha256);
